version: "3.1"

services:
  postgres:
    container_name: lms-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6000:5432"
    volumes:
      - lms-db:/var/lib/postgresql/data
  backend:
    container_name: lms-backend
    image: nodirshox/lms-backend:latest
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "80:3000"
volumes:
  lms-db:
    driver: local
